/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Dappazon } from "./Dappazon";
export * as factories from "./factories";
export { Dappazon__factory } from "./factories/Dappazon__factory";
